### ISSUE TITLE
Check amqp message body

### ISSUE THREAD

**Issue by MatthieuCutin** [WakeOnWeb/behat-contexts#1]
Checking for messages count is a good first step.
To go further, i want to be able to check message payload.

Something like :
Then next message in transport "async_internal" should contains :
"""{"id": "67c0c79d-fa17-4d0f-98a5-b80b0e35b349"}"""

**Comment by stephpy** [comment]
Done by @rousseauyoann here https://github.com/WakeOnWeb/behat-contexts/pull/7
